// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moukanvinxynnmzgqwtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vdWthbnZpbnh5bm5temdxd3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDcyNjYsImV4cCI6MjA3NDk4MzI2Nn0.Hfc7pF4RgiTgyrlkJUkrzfdgRxdZrsngG9m7zavJsAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});